# Generated by Django 3.2.16 on 2022-11-23 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custodian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('contact_name', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Custodian',
                'verbose_name_plural': 'Custodians',
            },
        ),
        migrations.AlterField(
            model_name='catalogueentry',
            name='custodian',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody', to='catalogue.custodian'),
        ),
    ]
