# Generated by Django 3.2.16 on 2022-11-09 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layersymbology',
            name='file',
        ),
        migrations.AddField(
            model_name='layersymbology',
            name='sld',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catalogueentry',
            name='active_layer',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogue.layersubmission'),
        ),
        migrations.AlterField(
            model_name='layerattribute',
            name='type',
            field=models.TextField(),
        ),
    ]
