# Generated by Django 3.2.16 on 2022-11-25 00:26

from django.db import migrations
from govapp.apps.catalogue import seed


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_add_custodians'),
    ]

    operations = [
        migrations.RunPython(seed.add_groups)
    ]
