# Generated by Django 3.2.16 on 2022-11-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_add_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogueentry',
            name='active_layer',
        ),
        migrations.AddField(
            model_name='layersubmission',
            name='is_active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
