# Generated by Django 3.2.16 on 2022-11-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_active_layer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueentry',
            name='status',
            field=models.IntegerField(choices=[(1, 'New Draft'), (2, 'Locked'), (3, 'Declined'), (4, 'Draft'), (5, 'Pending')], default=1),
        ),
    ]
