# Generated by Django 3.2.16 on 2022-11-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_alter_catalogueentry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='layersubmission',
            name='hash',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
