# Generated by Django 3.2.16 on 2022-12-07 05:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0006_layersubmission_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueentry',
            name='editors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
