# Generated by Django 3.2.16 on 2022-12-15 01:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_catalogueentry_editors'),
    ]

    operations = [
        migrations.AddField(
            model_name='layersubmission',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
