# Generated by Django 3.2.16 on 2023-01-13 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0008_layersubmission_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'Workspace',
                'verbose_name_plural': 'Workspaces',
            },
        ),
        migrations.AlterField(
            model_name='catalogueentry',
            name='editors',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catalogueentry',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='catalogue_entries', to='catalogue.workspace'),
        ),
    ]
