# Generated by Django 3.2.16 on 2023-01-19 04:17

from django.db import migrations, models
import govapp.apps.catalogue.validators


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_add_workspaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layersymbology',
            name='sld',
            field=models.TextField(validators=[govapp.apps.catalogue.validators.validate_xml, govapp.apps.catalogue.validators.validate_sld]),
        ),
    ]
