# Generated by Django 3.2.16 on 2022-11-25 00:26

from django.db import migrations
from .. import seed


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_add_workspaces'),
    ]

    operations = [
        migrations.RunPython(seed.add_default_workspace)
    ]
