# Generated by Django 3.2.16 on 2023-01-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_add_sld_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='type',
            field=models.IntegerField(choices=[(1, 'On New Data'), (2, 'On Lock'), (3, 'Both')]),
        ),
        migrations.AlterField(
            model_name='webhooknotification',
            name='type',
            field=models.IntegerField(choices=[(1, 'On New Data')]),
        ),
    ]
