# Generated by Django 3.2.16 on 2023-02-03 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_change_notification_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogueentry',
            name='workspace',
        ),
        migrations.DeleteModel(
            name='Workspace',
        ),
    ]
