# Generated by Django 3.2.17 on 2023-02-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_limit_editors_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueentry',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='layersubmission',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
