# Generated by Django 3.2.17 on 2023-02-16 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_optional_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layermetadata',
            name='name',
        ),
        migrations.RemoveField(
            model_name='layersubmission',
            name='name',
        ),
        migrations.RemoveField(
            model_name='layersubscription',
            name='name',
        ),
        migrations.RemoveField(
            model_name='layersymbology',
            name='name',
        ),
    ]
