# Generated by Django 3.2.19 on 2023-06-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_catalogueentry_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='layersubmission',
            name='geojson',
            field=models.TextField(blank=True, null=True),
        ),
    ]
