# Generated by Django 3.2.19 on 2023-06-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_layersubmission_geojson'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerAttributeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Layer Attribute Types',
                'verbose_name_plural': 'Layer Attribute Types',
            },
        ),
    ]
