# Generated by Django 3.2.19 on 2023-07-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_emailnotification_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueentry',
            name='type',
            field=models.IntegerField(choices=[(1, 'Special File'), (2, 'Subscription')], default=1),
        ),
    ]
