# Generated by Django 3.2.19 on 2023-07-17 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0020_catalogueentry_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueEntryPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('catalogue_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.catalogueentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
