# Generated by Django 3.2.19 on 2023-07-20 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0011_emailnotification_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0021_catalogueentrypermission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layersubscription',
            old_name='subscribed_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='catalogueentry',
            name='editors',
        ),
        migrations.RemoveField(
            model_name='layersubscription',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='layersubscription',
            name='status',
        ),
        migrations.AddField(
            model_name='layersubscription',
            name='connection_timeout',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='layersubscription',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='layersubscription',
            name='max_connections',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='layersubscription',
            name='read_timeout',
            field=models.IntegerField(default=10000, null=True),
        ),
        migrations.AddField(
            model_name='layersubscription',
            name='type',
            field=models.IntegerField(choices=[(1, 'Wms'), (2, 'Wfs')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layersubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='layersubscription',
            name='username',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layersubscription',
            name='userpassword',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layersubscription',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workspace', to='publisher.workspace'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='catalogueentrypermission',
            unique_together={('user', 'catalogue_entry')},
        ),
    ]
