# Generated by Django 3.2.19 on 2023-07-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_auto_20230720_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='layersubscription',
            name='database',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='layersubscription',
            name='fetch_size',
            field=models.IntegerField(default=1000, null=True),
        ),
        migrations.AddField(
            model_name='layersubscription',
            name='host',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='layersubscription',
            name='min_connections',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='layersubscription',
            name='port',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='layersubscription',
            name='schema',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='layersubscription',
            name='type',
            field=models.IntegerField(choices=[(1, 'Wms'), (2, 'Wfs'), (3, 'Post Gis')]),
        ),
        migrations.AlterField(
            model_name='layersubscription',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
