# Generated by Django 3.2.19 on 2023-07-27 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0023_auto_20230725_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='layersubscription',
            name='assigned_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_user_subscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='layersubscription',
            name='status',
            field=models.IntegerField(choices=[(1, 'New Draft'), (2, 'Locked'), (3, 'Declined'), (4, 'Draft'), (5, 'Pending')], default=1),
        ),
    ]
