# Generated by Django 3.2.19 on 2023-08-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_auto_20230727_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layersubscription',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='layersubscription',
            name='userpassword',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
