# Generated by Django 3.2.19 on 2023-08-07 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_auto_20230807_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='layersubscription',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='layersubscription',
            name='name',
            field=models.TextField(default='temp name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='layersubscription',
            name='catalogue_entry',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='catalogue.catalogueentry'),
        ),
    ]
