# Generated by Django 3.2.19 on 2023-08-09 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0026_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layersubscription',
            name='catalogue_entry',
        ),
        migrations.AddField(
            model_name='catalogueentry',
            name='layer_subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layer_subscription', to='catalogue.layersubscription'),
        ),
        migrations.AddField(
            model_name='catalogueentry',
            name='mapping_name',
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='catalogueentry',
            constraint=models.UniqueConstraint(fields=('mapping_name', 'layer_subscription'), name='unique_mapping_subscription'),
        ),
    ]
