# Generated by Django 3.2.20 on 2023-08-15 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_add_mapping_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueentry',
            name='mapping_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='catalogueentrypermission',
            name='catalogue_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalouge_permissions', to='catalogue.catalogueentry'),
        ),
    ]
