# Generated by Django 3.2.20 on 2023-09-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0028_auto_20230815_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueentry',
            name='sql_query',
            field=models.TextField(null=True),
        ),
    ]
