# Generated by Django 3.2.20 on 2023-09-14 03:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_add_field_sql_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueentry',
            name='layer_subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_entries', to='catalogue.layersubscription'),
        ),
        migrations.AlterField(
            model_name='catalogueentry',
            name='type',
            field=models.IntegerField(choices=[(1, 'Special File'), (2, 'Subscription'), (3, 'Subscription Query')], default=1),
        ),
        migrations.CreateModel(
            name='CustomQueryFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Every Minutes'), (2, 'Every Hours'), (3, 'Daily'), (4, 'Weekly'), (5, 'Monthly')])),
                ('every_minutes', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('every_hours', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('hour', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('minute', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)])),
                ('day_of_week', models.IntegerField(blank=True, choices=[(1, 'Mon'), (2, 'Tue'), (3, 'Wed'), (4, 'Thu'), (5, 'Fri'), (6, 'Sat'), (7, 'Sun')], null=True)),
                ('date', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('catalogue_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_queries', to='catalogue.catalogueentry')),
            ],
            options={
                'verbose_name': 'PostGisCustomQuery',
                'verbose_name_plural': 'PostGisCustomQueries',
            },
        ),
    ]
