# Generated by Django 3.2.20 on 2023-09-14 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0030_add_custon_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='customqueryfrequency',
            name='last_job_run',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='catalogueentry',
            name='type',
            field=models.IntegerField(choices=[(1, 'Spatial File'), (2, 'Subscription Wfs'), (3, 'Subscription Wms'), (4, 'Subscription Postgis'), (5, 'Subscription Query')], default=1),
        ),
        migrations.AlterField(
            model_name='customqueryfrequency',
            name='catalogue_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_query_frequencies', to='catalogue.catalogueentry'),
        ),
    ]
