# Generated by Django 3.2.25 on 2024-05-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0032_auto_20230915_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueentry',
            name='sql_query',
            field=models.TextField(blank=True, null=True),
        ),
    ]
