# Generated by Django 3.2.25 on 2024-06-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0033_alter_catalogueentry_sql_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='layermetadata',
            name='additional_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
