# Generated by Django 5.0.7 on 2024-08-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0034_layermetadata_additional_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueentry',
            name='permission_type',
            field=models.IntegerField(choices=[(1, 'Public'), (2, 'Restricted')], default=1),
        ),
    ]
