# Generated by Django 5.0.7 on 2024-08-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0037_remove_catalogueentrypermission_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueentrypermission',
            name='access_permission',
            field=models.IntegerField(choices=[(1, 'None'), (2, 'Read'), (3, 'Read and Write')], default=1),
        ),
    ]
