# Generated by Django 5.0.7 on 2024-08-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0039_catalogueentry_force_run_postgres_scanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customqueryfrequency',
            options={'verbose_name': 'PostGIS Query Frequency', 'verbose_name_plural': 'PostGIS Query Frequencies'},
        ),
        migrations.AlterField(
            model_name='catalogueentrypermission',
            name='access_permission',
            field=models.IntegerField(choices=[(1, 'None'), (2, 'Read'), (3, 'Read and Write')], default=2),
        ),
    ]
