# Generated by Django 5.0.7 on 2024-08-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0040_alter_customqueryfrequency_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueentrypermission',
            name='access_permission',
            field=models.IntegerField(choices=[(2, 'Read'), (3, 'Read and Write')], default=2),
        ),
    ]
