# Generated by Django 5.0.7 on 2024-09-12 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0041_alter_catalogueentrypermission_access_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueentrypermission',
            name='catalogue_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_permissions', to='catalogue.catalogueentry'),
        ),
    ]
