# Generated by Django 5.0.7 on 2024-10-31 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0043_alter_catalogueentry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueentry',
            name='permission_type',
            field=models.IntegerField(choices=[(1, 'Not restricted'), (2, 'Restricted')], default=1),
        ),
        migrations.CreateModel(
            name='LayerSubscriptionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('layer_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.layersubscription')),
            ],
            options={
                'verbose_name': 'Layer Subscription Data',
                'verbose_name_plural': 'Layer Subscription Data',
            },
        ),
    ]
