# Generated by Django 5.1.8 on 2025-05-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0044_alter_catalogueentry_permission_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layersubscription',
            name='ssl_mode',
            field=models.CharField(choices=[('disable', 'DISABLE'), ('allow', 'ALLOW'), ('prefer', 'PREFER'), ('require', 'REQUIRE'), ('verify-ca', 'VERIFY_CA'), ('verify-full', 'VERIFY_FULL')], default='allow', max_length=20),
        ),
    ]
