# Generated by Django 5.1.8 on 2025-05-20 00:43

import govapp.apps.catalogue.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0045_layersubscription_ssl_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layersymbology',
            name='sld',
            field=models.TextField(blank=True, default='', validators=[govapp.apps.catalogue.validators.validate_xml, govapp.apps.catalogue.validators.validate_sld]),
        ),
    ]
