# Generated by Django 5.1.8 on 2025-05-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0046_alter_layersymbology_sld'),
    ]

    operations = [
        migrations.AddField(
            model_name='layersymbology',
            name='use_raw',
            field=models.BooleanField(default=False),
        ),
    ]
