# Generated by Django 5.2.6 on 2025-10-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0047_layersymbology_use_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='layermetadata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='layersymbology',
            name='use_raw',
            field=models.BooleanField(default=True),
        ),
    ]
