# Generated by Django 5.2.6 on 2025-10-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0048_layermetadata_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layermetadata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
