# Generated by Django 5.2.15 on 2026-08-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0055_add_timestamps_to_allowed_crs'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueentry',
            name='overwrite_attributes',
            field=models.BooleanField(default=False, help_text="If True, the next scan/absorption of this Subscription Query will replace the Catalogue Entry's attribute (column) definition with whatever the query currently returns, instead of declining on a column structure mismatch. Automatically reset to False once consumed."),
        ),
    ]
