# Generated by Django 5.2.15 on 2026-08-20 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0056_catalogueentry_overwrite_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogueentry',
            name='overwrite_attributes',
        ),
    ]
