# Generated by Django 3.2.17 on 2023-02-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0003_limit_editors_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='cddppublishchannel',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geoserverpublishchannel',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publishentry',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
