# Generated by Django 3.2.18 on 2023-05-01 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0004_add_published_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoserverpublishchannel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='geoserverpublishchannel',
            name='name',
        ),
    ]
