# Generated by Django 3.2.17 on 2023-02-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0004_add_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cddppublishchannel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='geoserverpublishchannel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='publishentry',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
