# Generated by Django 3.2.18 on 2023-05-02 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0005_auto_20230501_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cddppublishchannel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cddppublishchannel',
            name='name',
        ),
    ]
