# Generated by Django 3.2.17 on 2023-02-16 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0005_optional_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cddppublishchannel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='geoserverpublishchannel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='publishentry',
            name='name',
        ),
    ]
