# Generated by Django 3.2.19 on 2023-05-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0007_remove_cddppublishchannel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cddppublishchannel',
            name='name',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
