# Generated by Django 3.2.19 on 2023-05-12 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0008_cddppublishchannel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cddppublishchannel',
            name='publish_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cddp_channel', to='publisher.publishentry'),
        ),
    ]
