# Generated by Django 3.2.19 on 2023-06-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0009_alter_cddppublishchannel_publish_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cddppublishchannel',
            name='format',
            field=models.IntegerField(choices=[(1, 'Geopackage'), (2, 'Shapefile'), (3, 'Geodatabase'), (4, 'Geojson')]),
        ),
    ]
