# Generated by Django 3.2.19 on 2023-07-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0010_alter_cddppublishchannel_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
