# Generated by Django 3.2.19 on 2023-07-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0011_emailnotification_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoServerPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Geoserver Pool',
                'verbose_name_plural': 'Geoserver Pools',
            },
        ),
    ]
