# Generated by Django 3.2.20 on 2023-08-28 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0013_add_geoserver_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoServerQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbology_only', models.BooleanField(default=True)),
                ('status', models.IntegerField(choices=[(0, 'Ready'), (1, 'On Publishing'), (2, 'Published'), (3, 'Failed')], default=0)),
                ('publishing_result', models.TextField(null=True)),
                ('success', models.BooleanField(default=False, null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publish_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geoserver_queues', to='publisher.publishentry')),
            ],
            options={
                'verbose_name': 'Geoserver Queue',
                'verbose_name_plural': 'Geoserver Queues',
            },
        ),
    ]
