# Generated by Django 3.2.20 on 2023-09-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0014_geoserverqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoserverpublishchannel',
            name='override_bbox',
            field=models.BooleanField(default=False),
        ),
    ]
