# Generated by Django 3.2.20 on 2023-09-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0016_geoserverpublishchannel_native_crs'),
    ]

    operations = [
        migrations.CreateModel(
            name='FTPServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.TextField(blank=True)),
                ('password', models.CharField(max_length=500, null=True)),
                ('username', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
