# Generated by Django 3.2.20 on 2023-09-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0017_auto_20230910_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='FTPPublishChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('format', models.IntegerField(choices=[(1, 'Geopackage'), (2, 'Shapefile'), (3, 'Geodatabase'), (4, 'Geojson')])),
                ('frequency', models.IntegerField(choices=[(1, 'On Change')])),
                ('path', models.TextField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
