# Generated by Django 3.2.20 on 2023-09-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0018_auto_20230910_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftpserver',
            name='host',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='ftpserver',
            name='password',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ftpserver',
            name='username',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
