# Generated by Django 3.2.20 on 2023-09-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0019_auto_20230911_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftpserver',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
