# Generated by Django 3.2.20 on 2023-09-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0020_auto_20230911_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftppublishchannel',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='ftppublishchannel',
            name='path',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
