# Generated by Django 3.2.20 on 2023-09-11 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0021_auto_20230911_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftppublishchannel',
            name='ftp_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publish_channels_ftp_server', to='publisher.ftpserver'),
        ),
    ]
