# Generated by Django 3.2.20 on 2023-09-11 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0022_auto_20230911_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftppublishchannel',
            name='publish_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ftp_channel', to='publisher.publishentry'),
        ),
    ]
