# Generated by Django 3.2.20 on 2023-09-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0023_auto_20230911_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftpserver',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
