# Generated by Django 3.2.20 on 2023-09-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0024_auto_20230911_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoserverpublishchannel',
            name='active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geoserverpublishchannel',
            name='llb_crs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='geoserverpublishchannel',
            name='llb_maxx',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='geoserverpublishchannel',
            name='llb_maxy',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='geoserverpublishchannel',
            name='llb_minx',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='geoserverpublishchannel',
            name='llb_miny',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='geoserverpublishchannel',
            name='native_crs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='geoserverpublishchannel',
            name='nbb_crs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='geoserverpublishchannel',
            name='nbb_maxx',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='geoserverpublishchannel',
            name='nbb_maxy',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='geoserverpublishchannel',
            name='nbb_minx',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='geoserverpublishchannel',
            name='nbb_miny',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='geoserverpublishchannel',
            name='srs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
