# Generated by Django 3.2.20 on 2023-09-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0025_add_bbox_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cddppublishchannel',
            name='xml_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
