# Generated by Django 3.2.20 on 2023-09-21 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publisher', '0026_cddppublishchannel_xml_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoserverqueue',
            name='submitter',
            field=models.ForeignKey(blank=None, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geoserver_queues', to=settings.AUTH_USER_MODEL),
        ),
    ]
