# Generated by Django 3.2.25 on 2024-04-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0027_geoserverqueue_submitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoserverpool',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
