# Generated by Django 3.2.25 on 2024-04-30 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0028_geoserverpool_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoserverpublishchannel',
            name='geo_server_pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.geoserverpool'),
        ),
    ]
