# Generated by Django 3.2.25 on 2024-05-01 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0029_geoserverpublishchannel_geo_server_pool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geoserverpublishchannel',
            old_name='geo_server_pool',
            new_name='geoserver_pool',
        ),
    ]
