# Generated by Django 3.2.25 on 2024-05-02 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0031_alter_geoserverpublishchannel_geoserver_pool'),
        ('publisher', '0032_alter_geoserverpublishchannel_unique_together'),
    ]

    operations = [
    ]
