# Generated by Django 3.2.25 on 2024-05-03 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0034_alter_geoserverpublishchannel_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoserverpublishchannel',
            name='publish_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geoserver_channel', to='publisher.publishentry'),
        ),
    ]
