# Generated by Django 3.2.25 on 2024-05-21 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0037_geoserverrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoServerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GeoServer Group',
                'verbose_name_plural': 'GeoServer Groups',
            },
        ),
        migrations.CreateModel(
            name='GeoServerGroupRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geoserver_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.geoservergroup')),
                ('geoserver_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.geoserverrole')),
            ],
            options={
                'verbose_name': 'GeoServer Role',
                'verbose_name_plural': 'GeoServer Roles',
            },
        ),
        migrations.AddField(
            model_name='geoservergroup',
            name='geoserver_roles',
            field=models.ManyToManyField(related_name='geoserver_groups', through='publisher.GeoServerGroupRole', to='publisher.GeoServerRole'),
        ),
    ]
