# Generated by Django 3.2.25 on 2024-06-10 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0040_alter_geoservergrouprole_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoserverpublishchannel',
            name='store_type',
            field=models.IntegerField(choices=[(1, 'GeoPackage'), (2, 'GeoTiff')], default=1),
        ),
        migrations.AlterField(
            model_name='cddppublishchannel',
            name='publish_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cddp_channels', to='publisher.publishentry'),
        ),
        migrations.AlterField(
            model_name='ftppublishchannel',
            name='publish_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ftp_channels', to='publisher.publishentry'),
        ),
    ]
