# Generated by Django 3.2.25 on 2024-06-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0041_auto_20240610_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoserverpublishchannel',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
