# Generated by Django 3.2.25 on 2024-06-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0043_geoservergroupuser_geoserverroleuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoservergroupuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='geoserverroleuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
