# Generated by Django 3.2.25 on 2024-07-04 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0044_auto_20240620_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoserverrole',
            name='parent_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_roles', to='publisher.geoserverrole'),
        ),
    ]
