# Generated by Django 5.0.7 on 2024-09-09 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0049_auto_20240726_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(max_length=255)),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('unlealthy', 'Unhealthy'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('last_check_time', models.DateTimeField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('geoserver_publish_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='publisher.geoserverpublishchannel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
