# Generated by Django 5.0.7 on 2024-09-09 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0050_layerhealthcheck'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LayerHealthCheck',
            new_name='GeoServerLayerHealthCheck',
        ),
    ]
