# Generated by Django 5.1.8 on 2025-05-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0054_geoserverpublishchannel_create_cached_layer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoserverpublishchannel',
            name='expire_client_cache_after_n_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='geoserverpublishchannel',
            name='expire_server_cache_after_n_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
