# Generated by Django 5.2.12 on 2026-03-17 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0060_add_queue_type_to_geoserver_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoserverqueue',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ready'), (1, 'On Publishing'), (2, 'Published'), (3, 'Failed'), (4, 'Upload In Progress'), (5, 'Upload Failed'), (6, 'Ready To Publish'), (7, 'Publish Failed')], default=0),
        ),
    ]
