# Generated by Django 5.2.17 on 2026-09-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0064_remove_active_from_geoserverlayergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoserverqueue',
            name='status',
            field=models.IntegerField(choices=[(0, 'Queued'), (1, 'Converting'), (2, 'Published'), (3, 'Conversion Failed'), (4, 'Awaiting Transfer'), (5, 'Transferring'), (6, 'Transfer Failed'), (7, 'Awaiting Publishing'), (8, 'Publishing Failed'), (9, 'Awaiting File Deletion')], default=0),
        ),
    ]
