# Generated by Django 3.2.16 on 2022-12-19 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationsLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField(choices=[(1, 'Email'), (2, 'Phone'), (3, 'Mail'), (4, 'Person'), (5, 'Other')])),
                ('to', models.TextField(blank=True)),
                ('cc', models.TextField(blank=True)),
                ('fromm', models.TextField(blank=True)),
                ('subject', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Communications Log Entry',
                'verbose_name_plural': 'Communications Log Entries',
            },
        ),
        migrations.CreateModel(
            name='CommunicationsLogDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='documents')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='logs.communicationslogentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications_log_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Communications Log Document',
                'verbose_name_plural': 'Communications Log Documents',
            },
        ),
        migrations.CreateModel(
            name='ActionsLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('what', models.TextField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actions Log Entry',
                'verbose_name_plural': 'Actions Log Entries',
            },
        ),
    ]
